services:
  hbbs:  #RustDesk ID (rendezvous / signaling) server
    container_name: hbbs   
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./data:/root
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21118:21118"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:  #RustDesk relay server
    container_name: hbbr 
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    ports:
      - "21117:21117"
      - "21119:21119"
    restart: unless-stopped

